objects/Appointment__c.object
<CustomObject>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Appointments</relationshipLabel>
        <relationshipName>Appointments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Physician__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Physician</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND 3</booleanFilter>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Physician</value>
            </filterItems>
            <filterItems>
                <field>Contact.Calendar_Shared__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Contact.Specialization__c</field>
                <operation>equals</operation>
                <valueField>$Source.Specialization__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Appointments (Physician)</relationshipLabel>
        <relationshipName>Appointments1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Specialization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Specialization</label>
        <referenceTo>Specialization__c</referenceTo>
        <relationshipLabel>Appointments</relationshipLabel>
        <relationshipName>Appointments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Appointment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Appointment Price Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CalenderAuthSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Refresh_Token__c</fullName>
        <label>Refresh Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Token__c</fullName>
        <label>Token</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>CalenderAuthSettings</label>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Calendar_Shared__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Calendar Shared?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Specialization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Specialization</label>
        <referenceTo>Specialization__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Physician</fullName>
        <active>true</active>
        <label>Physician</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/GoogleAPISettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Client_Id__c</fullName>
        <label>Client Id</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Client_Secret__c</fullName>
        <label>Client Secret</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Redirect_URL__c</fullName>
        <label>Redirect URL</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>GoogleAPISettings</label>
</CustomObject>

objects/Specialization__c.object
<CustomObject>
    <label>Specialization</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Specializations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/GoogleCalendarAPIService.cls
//Google Calendar API Service
public class GoogleCalendarAPIService {
    private static final GoogleAPISettings__c GOOGLE_API = GoogleAPISettings__c.getOrgDefaults();
    
    //Authorization
    public static Boolean getToken(String email,String code){
        Boolean isSuccess = false;
        try{
            
            String endPoint = 'https://www.googleapis.com/oauth2/v4/token';
            String client_id = GOOGLE_API.Client_Id__c;
            String client_secret = GOOGLE_API.Client_Secret__c;
            String redirect_uri = GOOGLE_API.Redirect_URL__c;
            
            String requestTokenBody = 'code='+code+'&client_id='+client_id+'&client_secret='+
                client_secret+'&redirect_uri='+redirect_uri+
                '&grant_type=authorization_code';
            
            Http http = new Http();
            httpRequest httpReq = new httpRequest();
            HttpResponse response = new HttpResponse();
            httpReq.setEndPoint(endPoint);
            httpReq.setBody(requestTokenBody);
            httpReq.setMethod('POST');
            httpReq.setTimeout(120000);
            httpReq.setHeader('Content-Type', 'application/x-www-form-urlencoded');
            response = http.send(httpReq);
            system.debug(response.getBody()); 
            
            if(response.getStatusCode() == 200){
                CalenderAuthSettings__c obj = CalenderAuthSettings__c.getInstance(email) != null ? 
                    CalenderAuthSettings__c.getInstance(email) : new CalenderAuthSettings__c(Name = email);
                Map<String,String> result = new Map<String,String>((Map<String,String>)JSON.deserialize(response.getBody(),Map<String,String>.class));
                obj.Token__c = result.get('access_token');
                obj.Refresh_Token__c  = result.get('refresh_token');
                upsert obj;
                List<Contact> contacts = new List<Contact>([SELECT Id,Calendar_Shared__c
                                                            FROM Contact
                                                            Where Email =: email
                                                            AND RecordType.DeveloperName = 'Physician'
                                                            AND Calendar_Shared__c  = false]); 
                for(Contact objCon : contacts){
                    objCon.Calendar_Shared__c = true;                      
                }
                update contacts;
                isSuccess = true;
            }
        }
        catch(Exception ex){
            
            system.debug(ex.getMessage()+ex.getStackTraceString());
        }
        
        return isSuccess;
    }
    
    //Fetch refresh token
    public static CalenderAuthSettings__c getRefreshToken(CalenderAuthSettings__c obj){
        
        try{
            
            String endPoint = 'https://www.googleapis.com/oauth2/v4/token';
            String client_id = GOOGLE_API.Client_Id__c;
            String client_secret = GOOGLE_API.Client_Secret__c;
            String redirect_uri = GOOGLE_API.Redirect_URL__c;
            
            String requestTokenBody = 'client_id='+client_id+'&client_secret='+
                client_secret+'&refresh_token='+ obj.Refresh_Token__c +
                '&grant_type=refresh_token';
            
            Http http = new Http();
            httpRequest httpReq = new httpRequest();
            HttpResponse response = new HttpResponse();
            httpReq.setEndPoint(endPoint);
            httpReq.setBody(requestTokenBody);
            httpReq.setMethod('POST');
            httpReq.setTimeout(120000);
            httpReq.setHeader('Content-Type', 'application/x-www-form-urlencoded');
            response = http.send(httpReq);
            system.debug(response.getBody());
            
            if(response.getStatusCode() == 200){
                
                Map<String,String> result = new Map<String,String>((Map<String,String>)JSON.deserialize(response.getBody(),Map<String,String>.class));
                obj.Token__c = result.get('access_token');
            }
        }
        catch(Exception ex){
            
            system.debug(ex.getMessage()+ex.getStackTraceString());
        }
        
        return obj;        
    }
    
    //Fetch events
    public static List<Map<String,Object>> getEvents(CalenderAuthSettings__c obj,String contextDate,String nextDate){
        
        List<Map<String,Object>> events = new List<Map<String,Object>>();
        try{
            Http http = new Http();
            httpRequest httpReq = new httpRequest();
            HttpResponse response = new HttpResponse();
            httpReq.setEndPoint('https://www.googleapis.com/calendar/v3/calendars/primary/events'+
                                '?timeMin='+contextDate+'T00:00:00Z'+
                                '&timeMax='+nextDate+'T00:00:00Z');
            httpReq.setMethod('GET');
            httpReq.setHeader('Content-Type', 'application/json');
            httpReq.setHeader('Authorization', 'Bearer '+ obj.Token__c);
            httpReq.setTimeout(120000);
            response = http.send(httpReq);
            system.debug(response.getBody());
            
            if(response.getStatusCode() == 200){
                Map<String,Object> results = new Map<String,Object>((Map<String, Object>) JSON.deserializeUntyped(response.getBody()));
                
                for(Object item : (List<Object>) results.get('items')){
                    Map<String,Object> event = ( Map<String,Object>) item;
                    String startT = '';
                    String endT = '';
                    if(event.containsKey('start')){
                        Map<String,Object> startDate = ( Map<String,Object>) event.get('start');
                        startT = String.valueOf(startDate.get('dateTime'));
                    }
                    if(event.containsKey('end')){
                        Map<String,Object> endDate = ( Map<String,Object>) event.get('end');
                        endT = String.valueOf(endDate.get('dateTime'));
                    }
                    if(String.isNotBlank(startT) || String.isNotBlank(endT)){
                        events.add(new Map<String,Object>{'start' => startT,
                            'end' => endT,
                            'overlap' => false
                            });
                    }
                }
            }
            else{
                obj = getRefreshToken(obj);
                events = getEvents(obj,contextDate,nextDate);
                upsert obj;
            }
        }
        catch(Exception ex){
            system.debug(ex.getMessage()+ex.getStackTraceString());
        }
        return events;
    }
    
    //Create event
    public static Boolean createEvent(CalenderAuthSettings__c obj,String patientId,String physicianId,String startTime,String endTime){
        
        Boolean isSuccess = false;
        try{
            Http http = new Http();
            httpRequest httpReq = new httpRequest();
            HttpResponse response = new HttpResponse();
            httpReq.setEndPoint('https://www.googleapis.com/calendar/v3/calendars/primary/events?sendNotifications=true&sendUpdates=all');
            httpReq.setMethod('POST');
            httpReq.setTimeout(120000);
            httpReq.setHeader('Content-Type', 'application/json');
            httpReq.setHeader('Authorization', 'Bearer '+ obj.Token__c);
            Contact objPatient = [SELECT Id,Email FROM Contact WHERE Id =: patientId WITH SECURITY_ENFORCED][0];
            
            String body = '{"summary": "Appointment scheduled at Medical Clinic",'+
                '"location": "Medical Clinic",'+
                '"attendees":[{"email": "'+objPatient.Email+'"}],'+
                '"start":{"dateTime": "'+startTime+'","timeZone": "Asia/Kolkata"},'+
                '"end":{"dateTime": "'+endTime+'","timeZone": "Asia/Kolkata"}}';
            httpReq.setBody(body);
            response = http.send(httpReq);
            system.debug(response.getBody());
            
            if(response.getStatusCode() != 200){
                
                obj = getRefreshToken(obj);
                createEvent(obj,patientId,physicianId,startTime,endTime);
                upsert obj;
                isSuccess = true;
            }
            else{
                Contact objPhy = [SELECT Id,Specialization__c  FROM Contact WHERE Id =: physicianId WITH SECURITY_ENFORCED][0];
                Appointment__c  objApp =  new Appointment__c (Physician__c  = objPhy.Id,
                                                              Patient__c   = objPatient.Id,
                                                              Specialization__c  = objPhy.Specialization__c,
                                                              Start_Time__c  = DateTime.ValueofGmt(startTime.replace('T', ' ')),
                                                              End_Time__c  = DateTime.ValueofGmt(endTime.replace('T', ' ')));
                insert objApp;
            }
        }
        catch(Exception ex){
            system.debug(ex.getMessage()+ex.getStackTraceString());
        }
        return isSuccess;
    }
}