objects/CalenderAuthSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Refresh_Token__c</fullName>
        <label>Refresh Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Token__c</fullName>
        <label>Token</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>CalenderAuthSettings</label>
</CustomObject>

classes/MedicalClinicTests.cls
@isTest
private class MedicalClinicTests {
    
    @isTest static void test_CalenderAuthController() {
        new CalenderAuthController().register();
    }
    
    @isTest static void test_AppointmentBookingController() {
        insert new CalenderAuthSettings__c(Name = 'oswinchris@gmail.com',Token__c='Sample',Refresh_Token__c='Sample');
        AppointmentBookingController.getPhysicians();
        AppointmentBookingController.getEvents('oswinchris@gmail.com','','');
        AppointmentBookingController.createEvent('oswinchris@gmail.com','','','','');
        GoogleCalendarAPIService.getRefreshToken(new CalenderAuthSettings__c(Refresh_Token__c = 'Sample'));
    } 
}