objects/CalenderAuthSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>CalenderAuthSettings</label>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Calendar_Shared__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Calendar Shared?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Specialization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Specialization</label>
        <referenceTo>Specialization__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Physician</fullName>
        <active>true</active>
        <label>Physician</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Specialization__c.object
<CustomObject>
    <fields>
        <fullName>Appointment_Price__c</fullName>
        <label>Appointment Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Specialization</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Specializations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AppointmentBookingController.cls
public class AppointmentBookingController {
    
    @AuraEnabled
    public static Map<Id,Contact> getPhysicians(){
        return new Map<Id,Contact>([SELECT Id,Name,Email,Specialization__c,Specialization__r.Name,Specialization__r.Appointment_Price__c 
                                    FROM Contact
                                    WHERE RecordType.DeveloperName = 'Physician'
                                    AND Calendar_Shared__c  = true
                                    ORDER By Specialization__r.Name ASC]);
    }
    
    @AuraEnabled
    public static List<Map<String,Object>> getEvents(String email,String contextDate,String nextDate){
        return GoogleCalendarAPIService.getEvents(CalenderAuthSettings__c.getInstance(email),contextDate,nextDate);  
    }
    
    @AuraEnabled
    public static Boolean createEvent(String email,String patientId,String physicianId,String startTime,String endTime){
        
        return GoogleCalendarAPIService.createEvent(CalenderAuthSettings__c.getInstance(email),patientId,physicianId,startTime,endTime); 
    }
}